// autogenerated 2016-07-17 12:39:46. See TU/clang.R
void
showSizeofs()
{
fprintf(stdout, "CUDAStructSizes = c(\n");
fprintf(stdout, " int = %dL,\n", (int) sizeof(int));
fprintf(stdout, " long = %dL,\n", (int) sizeof(long));
fprintf(stdout, " short = %dL,\n", (int) sizeof(short));
fprintf(stdout, " char = %dL,\n", (int) sizeof(char));
fprintf(stdout, " float = %dL,\n", (int) sizeof(float));
fprintf(stdout, " double = %dL,\n", (int) sizeof(double));
fprintf(stdout, " CUuuid_st = %dL,\n", (int) sizeof(CUuuid_st));
fprintf(stdout, " CUipcEventHandle_st = %dL,\n", (int) sizeof(CUipcEventHandle_st));
fprintf(stdout, " CUipcMemHandle_st = %dL,\n", (int) sizeof(CUipcMemHandle_st));
fprintf(stdout, " CUdevprop_st = %dL,\n", (int) sizeof(CUdevprop_st));
fprintf(stdout, " CUDA_MEMCPY2D_st = %dL,\n", (int) sizeof(CUDA_MEMCPY2D_st));
fprintf(stdout, " CUDA_MEMCPY3D_st = %dL,\n", (int) sizeof(CUDA_MEMCPY3D_st));
fprintf(stdout, " CUDA_MEMCPY3D_PEER_st = %dL,\n", (int) sizeof(CUDA_MEMCPY3D_PEER_st));
fprintf(stdout, " CUDA_ARRAY_DESCRIPTOR_st = %dL,\n", (int) sizeof(CUDA_ARRAY_DESCRIPTOR_st));
fprintf(stdout, " CUDA_ARRAY3D_DESCRIPTOR_st = %dL,\n", (int) sizeof(CUDA_ARRAY3D_DESCRIPTOR_st));
fprintf(stdout, " CUDA_RESOURCE_DESC_st = %dL,\n", (int) sizeof(CUDA_RESOURCE_DESC_st));
fprintf(stdout, " CUDA_TEXTURE_DESC_st = %dL,\n", (int) sizeof(CUDA_TEXTURE_DESC_st));
fprintf(stdout, " CUDA_RESOURCE_VIEW_DESC_st = %dL,\n", (int) sizeof(CUDA_RESOURCE_VIEW_DESC_st));
fprintf(stdout, " CUDA_POINTER_ATTRIBUTE_P2P_TOKENS_st = %dL,\n", (int) sizeof(CUDA_POINTER_ATTRIBUTE_P2P_TOKENS_st));
fprintf(stdout, " cudaChannelFormatDesc = %dL,\n", (int) sizeof(cudaChannelFormatDesc));
fprintf(stdout, " cudaPitchedPtr = %dL,\n", (int) sizeof(cudaPitchedPtr));
fprintf(stdout, " cudaExtent = %dL,\n", (int) sizeof(cudaExtent));
fprintf(stdout, " cudaPos = %dL,\n", (int) sizeof(cudaPos));
fprintf(stdout, " cudaMemcpy3DParms = %dL,\n", (int) sizeof(cudaMemcpy3DParms));
fprintf(stdout, " cudaMemcpy3DPeerParms = %dL,\n", (int) sizeof(cudaMemcpy3DPeerParms));
fprintf(stdout, " cudaResourceDesc = %dL,\n", (int) sizeof(cudaResourceDesc));
fprintf(stdout, " cudaResourceViewDesc = %dL,\n", (int) sizeof(cudaResourceViewDesc));
fprintf(stdout, " cudaPointerAttributes = %dL,\n", (int) sizeof(cudaPointerAttributes));
fprintf(stdout, " cudaFuncAttributes = %dL,\n", (int) sizeof(cudaFuncAttributes));
fprintf(stdout, " cudaDeviceProp = %dL,\n", (int) sizeof(cudaDeviceProp));
fprintf(stdout, " cudaIpcEventHandle_st = %dL,\n", (int) sizeof(cudaIpcEventHandle_st));
fprintf(stdout, " cudaIpcMemHandle_st = %dL,\n", (int) sizeof(cudaIpcMemHandle_st));
fprintf(stdout, " cudaTextureDesc = %dL\n", (int) sizeof(cudaTextureDesc));
fprintf(stdout, ")\n");
}
